export const spyLocations: Record<string, string> = {
    airport: "Аэропорт",
    bank: "Банк",
    hospital: "Больница",
    military_base: "Военная база",
    train_station: "Вокзал",
    hotel: "Гостиница",
    kindergarten: "Детский сад",
    zoo: "Зоопарк",
    casino: "Казино",
    cinema: "Кинотеатр",
    ship: "Корабль",
    space_station: "Космическая станция",
    coffee_shop: "Кофейня",
    laboratory: "Лаборатория",
    lighthouse: "Маяк",
    museum: "Музей",
    oil_platform: "Нефтяная платформа",
    beach: "Пляж",
    submarine: "Подводная лодка",
    police_station: "Полицейский участок",
    embassy: "Посольство",
    post_office: "Почта",
    fire_station: "Пожарная станция",
    restaurant: "Ресторан",
    market: "Рынок",
    airplane: "Самолёт",
    spa: "Спа-салон",
    stadium: "Спортивный стадион",
    supermarket: "Супермаркет",
    prison: "Тюрьма",
    university: "Университет",
    photo_studio: "Фотостудия",
    circus: "Цирк",
    school: "Школа",
    yacht: "Яхта",
    castle: "Замок",
    pirate_ship: "Пиратский корабль",
    theatre: "Театр",
    library: "Библиотека",
    monastery: "Монастырь",
    mine: "Шахта",
    farm: "Ферма",
    antarctic_station: "Антарктическая станция",
    ski_resort: "Горнолыжный курорт",
    chemical_plant: "Нефтехимический завод",
    secret_bunker: "Секретный бункер",
    mall: "Торговый центр",
    ferry: "Паром",
    jungle: "Джунгли",
}
